# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cac30f4278afe846f250ee230636950d7b80663a9e1bca78154fa3c7253d42cef9d77f9554d19365058c8be6d907eec6c04ca8ab69d2a9ea89a8f3b811b1f933

test:
  secret_key_base: 8fc2befb962e5b19ba4f912bc1e564d0c6a88baad04f5faec68ca70ccb668cde953987166c4971df3908da3cb22710ba687e3a2c6fae91ab9dc597660c2e0294

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
